"""
Independent post-solve validation layer.

Checks that the timetable generated by the solver complies with all database-level
hard constraints. This runs entirely separately from the solver logic, acting as
a double-check/audit layer to ensure no bug in solver variables, model building,
or data expansion has caused a constraint violation to slip through.
"""
from app.models.academic import RoomType
from app.schemas.timetable import TimetableGenerationRequest, TimetableEntryResult, ConflictDetail


def validate_generated_timetable(
    request: TimetableGenerationRequest,
    entries: list[TimetableEntryResult]
) -> tuple[bool, list[ConflictDetail]]:
    """
    Validates a list of TimetableEntryResult against the request parameters.
    Returns: (passed: bool, list[ConflictDetail])
    """
    conflicts = []

    # Map lookups
    divisions_by_id = {d.id: d for d in request.divisions}
    subjects_by_id = {s.id: s for s in request.subjects}
    rooms_by_id = {r.id: r for r in request.rooms}
    unavailable = {(u.faculty_id, u.day, u.slot) for u in request.unavailability}
    break_slots_set = set(request.break_slots)

    # 1. Resource double-booking tracking
    # Key: (resource_id, day, slot) -> Entry
    faculty_slots = {}
    division_slots = {}
    room_slots = {}

    # Subject session counters: (division_id, subject_id) -> count of slots
    subject_counts = {}

    for index, entry in enumerate(entries):
        division = divisions_by_id.get(entry.division_id)
        subject = subjects_by_id.get(entry.subject_id)
        room = rooms_by_id.get(entry.room_id)

        # Basic referential integrity
        if not division:
            conflicts.append(ConflictDetail(
                type="validation_missing_division",
                details=f"Entry {index} references non-existent division {entry.division_id}"
            ))
            continue
        if not subject:
            conflicts.append(ConflictDetail(
                type="validation_missing_subject",
                details=f"Entry {index} references non-existent subject {entry.subject_id}"
            ))
            continue
        if not room:
            conflicts.append(ConflictDetail(
                type="validation_missing_room",
                details=f"Entry {index} references non-existent room {entry.room_id}"
            ))
            continue

        div_name = division.name
        sub_name = subject.name
        room_name = room.name

        # 2. Break slot check
        if entry.slot in break_slots_set:
            conflicts.append(ConflictDetail(
                type="validation_break_violation",
                subject=sub_name,
                division=div_name,
                room=room_name,
                details=f"Scheduled during break slot {entry.slot}"
            ))

        # 3. Faculty unavailability check
        if (entry.faculty_id, entry.day, entry.slot) in unavailable:
            conflicts.append(ConflictDetail(
                type="validation_faculty_unavailable",
                subject=sub_name,
                division=div_name,
                faculty=entry.faculty_id,
                details=f"Faculty scheduled during declared unavailable slot (Day {entry.day}, Slot {entry.slot})"
            ))

        # 4. Double booking checks
        fac_key = (entry.faculty_id, entry.day, entry.slot)
        if fac_key in faculty_slots:
            prev = faculty_slots[fac_key]
            conflicts.append(ConflictDetail(
                type="validation_faculty_double_booked",
                subject=sub_name,
                division=div_name,
                faculty=entry.faculty_id,
                details=f"Faculty is scheduled for both '{sub_name}' (Div: {div_name}) and '{prev.get('subject')}' (Div: {prev.get('division')}) at Day {entry.day}, Slot {entry.slot}"
            ))
        faculty_slots[fac_key] = {"subject": sub_name, "division": div_name}

        div_key = (entry.division_id, entry.day, entry.slot)
        if div_key in division_slots:
            prev = division_slots[div_key]
            conflicts.append(ConflictDetail(
                type="validation_division_double_booked",
                subject=sub_name,
                division=div_name,
                details=f"Division {div_name} is double booked for '{sub_name}' and '{prev.get('subject')}' at Day {entry.day}, Slot {entry.slot}"
            ))
        division_slots[div_key] = {"subject": sub_name}

        room_key = (entry.room_id, entry.day, entry.slot)
        if room_key in room_slots:
            prev = room_slots[room_key]
            conflicts.append(ConflictDetail(
                type="validation_room_double_booked",
                subject=sub_name,
                division=div_name,
                room=room_name,
                details=f"Room {room_name} is occupied by both '{sub_name}' (Div: {div_name}) and '{prev.get('subject')}' (Div: {prev.get('division')}) at Day {entry.day}, Slot {entry.slot}"
            ))
        room_slots[room_key] = {"subject": sub_name, "division": div_name}

        # 5. Room capacity check
        if room.capacity < division.strength:
            conflicts.append(ConflictDetail(
                type="validation_capacity_mismatch",
                subject=sub_name,
                division=div_name,
                room=room_name,
                details=f"Room {room_name} capacity ({room.capacity}) is smaller than division strength ({division.strength})"
            ))

        # 6. Room type check
        required_type = RoomType.LAB if entry.is_lab_block else RoomType.LECTURE
        if room.type != required_type:
            conflicts.append(ConflictDetail(
                type="validation_room_type_mismatch",
                subject=sub_name,
                division=div_name,
                room=room_name,
                details=f"Subject '{sub_name}' requires room type {required_type.value} but was placed in {room.type.value}"
            ))


        # Count session slots
        count_key = (entry.division_id, entry.subject_id)
        subject_counts[count_key] = subject_counts.get(count_key, 0) + 1

    # 7. Total weekly lectures check
    for assignment in request.assignments:
        subject = subjects_by_id.get(assignment.subject_id)
        division = divisions_by_id.get(assignment.division_id)
        if not subject or not division:
            continue

        expected = subject.weekly_lectures
        if subject.is_lab:
            expected += subject.lab_sessions_per_week * subject.lab_block_size

        actual = subject_counts.get((assignment.division_id, assignment.subject_id), 0)
        if actual != expected:
            conflicts.append(ConflictDetail(
                type="validation_session_count_mismatch",
                subject=subject.name,
                division=division.name,
                details=f"Expected {expected} slots for subject '{subject.name}' (Div: {division.name}) but actually scheduled {actual} slots"
            ))

    passed = len(conflicts) == 0
    return passed, conflicts
